language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_GEM_VERSION="2.7.19"
  - PUPPET_GEM_VERSION="~> 3.1.0"
matrix:
  allow_failures:
    - rvm: 2.0.0
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="2.7.19"
notifications:
  email: false
